# Generated by Django 5.2.14 on 2026-06-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120, verbose_name='nombre del cliente')),
                ('phone', models.CharField(max_length=20, verbose_name='teléfono / WhatsApp')),
                ('delivery_place', models.CharField(blank=True, max_length=180, verbose_name='lugar de entrega')),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='fecha/hora deseada')),
                ('payment_method', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia / SPEI'), ('oxxo', 'Depósito OXXO'), ('otro', 'Otro / A definir')], max_length=20, verbose_name='método de pago')),
                ('notes', models.TextField(blank=True, verbose_name='notas adicionales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='estado')),
                ('whatsapp_message', models.TextField(blank=True, verbose_name='mensaje de WhatsApp generado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.customerorder', verbose_name='pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto del pedido',
                'verbose_name_plural': 'productos del pedido',
            },
        ),
    ]
