# Generated by Django 5.2.14 on 2026-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promo_images/', verbose_name='imagen')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='inicia')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='termina')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
            ],
            options={
                'verbose_name': 'promoción',
                'verbose_name_plural': 'promociones',
                'ordering': ['-created_at'],
            },
        ),
    ]
