# Generated by Django 5.2.14 on 2026-06-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='CookiesLab', max_length=120, verbose_name='nombre del negocio')),
                ('slogan', models.CharField(default='Galletitas que alegran tu día', max_length=180, verbose_name='slogan')),
                ('hero_title', models.CharField(default='Cookies recién hechas para salvar tu día', max_length=180, verbose_name='título principal')),
                ('hero_subtitle', models.TextField(blank=True, default='De estudiantes para estudiantes. Pide por WhatsApp y coordina tu entrega.', verbose_name='subtítulo principal')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Solo números, ejemplo: 528441234567', max_length=20, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/coookieslab/', verbose_name='Instagram')),
                ('location_text', models.CharField(blank=True, default='Saltillo, Coahuila', max_length=180, verbose_name='ubicación')),
                ('delivery_notes', models.TextField(blank=True, default='Entregas sujetas a disponibilidad. Coordina horario y punto por WhatsApp.', verbose_name='notas de entrega')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brand/', verbose_name='logo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado')),
            ],
            options={
                'verbose_name': 'configuración del negocio',
                'verbose_name_plural': 'configuración del negocio',
            },
        ),
    ]
